<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>

    <LangVersion>latest</LangVersion>

    <Nullable>enable</Nullable>

    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>E:\SteamLibrary\steamapps\common\Cuphead\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>

    <Reference Include="0Harmony">
      <HintPath>E:\SteamLibrary\steamapps\common\Cuphead\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>

    <Reference Include="Assembly-CSharp">
      <HintPath>E:\SteamLibrary\steamapps\common\Cuphead\Cuphead_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine">
      <HintPath>E:\SteamLibrary\steamapps\common\Cuphead\Cuphead_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>E:\SteamLibrary\steamapps\common\Cuphead\Cuphead_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>

  </ItemGroup>

</Project>
